name: python3-defaults
on: ["push", "workflow_dispatch"]
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      build_options: nobench nocheck nopgo
